apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: calendar-1
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: calendar-dep 
      eventSourceName: calendar-eventsource
      eventName: first-event 
  triggers:
    - template:
        name: calendar-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: calendar-2-workflow-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    value: Goodbye world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]